/**
 * CatalystLab 42 Anycast Edge PoPs Registry
 * Synchronous Telemetry Mesh & Global Interceptors
 */

export type PoPTier = 1 | 2 | 3;
export type PoPStatus = 'optimal' | 'degraded' | 'critical';

export interface EdgePoP {
  id: string;
  code: string;
  region: string;
  location: string;
  country: string;
  coordinates: [number, number]; // [lat, lon]
  tier: PoPTier;
  status: PoPStatus;
  ttfbMs: number;
  tlsRtt: string;
  http3: boolean;
  activeProbes: number;
  requestsPerSec: number;
  carbonIntensity: number; // gCO2/kWh
  ipPrefix: string;
}

export const EDGE_POPS: EdgePoP[] = [
  // North America
  {
    id: 'pop-iad',
    code: 'IAD',
    region: 'US-East (Virginia)',
    location: 'Ashburn / Washington D.C.',
    country: 'United States',
    coordinates: [39.0438, -77.4874],
    tier: 1,
    status: 'optimal',
    ttfbMs: 11.4,
    tlsRtt: '1.2ms (0-RTT)',
    http3: true,
    activeProbes: 384,
    requestsPerSec: 14200,
    carbonIntensity: 0.18,
    ipPrefix: '198.51.100.0/24',
  },
  {
    id: 'pop-sfo',
    code: 'SFO',
    region: 'US-West (N. California)',
    location: 'San Francisco / Silicon Valley',
    country: 'United States',
    coordinates: [37.7749, -122.4194],
    tier: 1,
    status: 'optimal',
    ttfbMs: 12.8,
    tlsRtt: '1.4ms (0-RTT)',
    http3: true,
    activeProbes: 340,
    requestsPerSec: 12900,
    carbonIntensity: 0.11,
    ipPrefix: '198.51.101.0/24',
  },
  {
    id: 'pop-lax',
    code: 'LAX',
    region: 'US-West (S. California)',
    location: 'Los Angeles',
    country: 'United States',
    coordinates: [34.0522, -118.2437],
    tier: 1,
    status: 'optimal',
    ttfbMs: 14.1,
    tlsRtt: '1.5ms (0-RTT)',
    http3: true,
    activeProbes: 290,
    requestsPerSec: 11200,
    carbonIntensity: 0.14,
    ipPrefix: '198.51.102.0/24',
  },
  {
    id: 'pop-ord',
    code: 'ORD',
    region: 'US-Central (Illinois)',
    location: 'Chicago',
    country: 'United States',
    coordinates: [41.8781, -87.6298],
    tier: 1,
    status: 'optimal',
    ttfbMs: 15.6,
    tlsRtt: '1.6ms (0-RTT)',
    http3: true,
    activeProbes: 260,
    requestsPerSec: 9800,
    carbonIntensity: 0.22,
    ipPrefix: '198.51.103.0/24',
  },
  {
    id: 'pop-dfw',
    code: 'DFW',
    region: 'US-South (Texas)',
    location: 'Dallas / Fort Worth',
    country: 'United States',
    coordinates: [32.7767, -96.7970],
    tier: 1,
    status: 'optimal',
    ttfbMs: 13.9,
    tlsRtt: '1.3ms (0-RTT)',
    http3: true,
    activeProbes: 240,
    requestsPerSec: 8900,
    carbonIntensity: 0.25,
    ipPrefix: '198.51.104.0/24',
  },
  {
    id: 'pop-yyz',
    code: 'YYZ',
    region: 'CA-East (Ontario)',
    location: 'Toronto',
    country: 'Canada',
    coordinates: [43.6532, -79.3832],
    tier: 2,
    status: 'optimal',
    ttfbMs: 17.2,
    tlsRtt: '1.8ms (0-RTT)',
    http3: true,
    activeProbes: 180,
    requestsPerSec: 6400,
    carbonIntensity: 0.08,
    ipPrefix: '198.51.105.0/24',
  },
  {
    id: 'pop-mex',
    code: 'MEX',
    region: 'MX-Central (CDMX)',
    location: 'Mexico City',
    country: 'Mexico',
    coordinates: [19.4326, -99.1332],
    tier: 2,
    status: 'optimal',
    ttfbMs: 24.5,
    tlsRtt: '2.4ms (0-RTT)',
    http3: true,
    activeProbes: 140,
    requestsPerSec: 4900,
    carbonIntensity: 0.31,
    ipPrefix: '198.51.106.0/24',
  },

  // South America
  {
    id: 'pop-bog',
    code: 'BOG',
    region: 'SA-North (Cundinamarca)',
    location: 'Bogotá',
    country: 'Colombia',
    coordinates: [4.7110, -74.0721],
    tier: 3,
    status: 'degraded',
    ttfbMs: 38.4,
    tlsRtt: '4.2ms (1-RTT fallback)',
    http3: false,
    activeProbes: 95,
    requestsPerSec: 2800,
    carbonIntensity: 0.16,
    ipPrefix: '198.51.107.0/24',
  },
  {
    id: 'pop-lim',
    code: 'LIM',
    region: 'SA-West (Lima)',
    location: 'Lima',
    country: 'Peru',
    coordinates: [-12.0464, -77.0428],
    tier: 3,
    status: 'optimal',
    ttfbMs: 32.1,
    tlsRtt: '3.1ms (0-RTT)',
    http3: true,
    activeProbes: 85,
    requestsPerSec: 2400,
    carbonIntensity: 0.19,
    ipPrefix: '198.51.108.0/24',
  },
  {
    id: 'pop-scl',
    code: 'SCL',
    region: 'SA-South (Santiago)',
    location: 'Santiago',
    country: 'Chile',
    coordinates: [-33.4489, -70.6693],
    tier: 2,
    status: 'optimal',
    ttfbMs: 28.7,
    tlsRtt: '2.8ms (0-RTT)',
    http3: true,
    activeProbes: 110,
    requestsPerSec: 3600,
    carbonIntensity: 0.12,
    ipPrefix: '198.51.109.0/24',
  },
  {
    id: 'pop-eze',
    code: 'EZE',
    region: 'SA-South (Buenos Aires)',
    location: 'Buenos Aires',
    country: 'Argentina',
    coordinates: [-34.6037, -58.3816],
    tier: 2,
    status: 'optimal',
    ttfbMs: 29.4,
    tlsRtt: '2.9ms (0-RTT)',
    http3: true,
    activeProbes: 120,
    requestsPerSec: 4100,
    carbonIntensity: 0.28,
    ipPrefix: '198.51.110.0/24',
  },
  {
    id: 'pop-gru',
    code: 'GRU',
    region: 'SA-East (São Paulo)',
    location: 'São Paulo',
    country: 'Brazil',
    coordinates: [-23.5505, -46.6333],
    tier: 1,
    status: 'optimal',
    ttfbMs: 19.8,
    tlsRtt: '1.9ms (0-RTT)',
    http3: true,
    activeProbes: 230,
    requestsPerSec: 8400,
    carbonIntensity: 0.09,
    ipPrefix: '198.51.111.0/24',
  },

  // Europe & Middle East
  {
    id: 'pop-lhr',
    code: 'LHR',
    region: 'EU-West (London)',
    location: 'London',
    country: 'United Kingdom',
    coordinates: [51.5074, -0.1278],
    tier: 1,
    status: 'optimal',
    ttfbMs: 9.8,
    tlsRtt: '1.0ms (0-RTT)',
    http3: true,
    activeProbes: 410,
    requestsPerSec: 15600,
    carbonIntensity: 0.15,
    ipPrefix: '198.51.112.0/24',
  },
  {
    id: 'pop-dub',
    code: 'DUB',
    region: 'EU-West (Ireland)',
    location: 'Dublin',
    country: 'Ireland',
    coordinates: [53.3498, -6.2603],
    tier: 2,
    status: 'optimal',
    ttfbMs: 12.4,
    tlsRtt: '1.2ms (0-RTT)',
    http3: true,
    activeProbes: 190,
    requestsPerSec: 6800,
    carbonIntensity: 0.17,
    ipPrefix: '198.51.113.0/24',
  },
  {
    id: 'pop-cdg',
    code: 'CDG',
    region: 'EU-West (Paris)',
    location: 'Paris',
    country: 'France',
    coordinates: [48.8566, 2.3522],
    tier: 1,
    status: 'optimal',
    ttfbMs: 10.5,
    tlsRtt: '1.1ms (0-RTT)',
    http3: true,
    activeProbes: 320,
    requestsPerSec: 11800,
    carbonIntensity: 0.06,
    ipPrefix: '198.51.114.0/24',
  },
  {
    id: 'pop-ams',
    code: 'AMS',
    region: 'EU-Northwest (Amsterdam)',
    location: 'Amsterdam',
    country: 'Netherlands',
    coordinates: [52.3676, 4.9041],
    tier: 1,
    status: 'optimal',
    ttfbMs: 8.9,
    tlsRtt: '0.9ms (0-RTT)',
    http3: true,
    activeProbes: 390,
    requestsPerSec: 14700,
    carbonIntensity: 0.20,
    ipPrefix: '198.51.115.0/24',
  },
  {
    id: 'pop-fra',
    code: 'FRA',
    region: 'EU-Central (Frankfurt)',
    location: 'Frankfurt',
    country: 'Germany',
    coordinates: [50.1109, 8.6821],
    tier: 1,
    status: 'optimal',
    ttfbMs: 9.2,
    tlsRtt: '1.0ms (0-RTT)',
    http3: true,
    activeProbes: 420,
    requestsPerSec: 16100,
    carbonIntensity: 0.24,
    ipPrefix: '198.51.116.0/24',
  },
  {
    id: 'pop-mad',
    code: 'MAD',
    region: 'EU-South (Madrid)',
    location: 'Madrid',
    country: 'Spain',
    coordinates: [40.4168, -3.7038],
    tier: 2,
    status: 'optimal',
    ttfbMs: 16.1,
    tlsRtt: '1.6ms (0-RTT)',
    http3: true,
    activeProbes: 170,
    requestsPerSec: 5900,
    carbonIntensity: 0.13,
    ipPrefix: '198.51.117.0/24',
  },
  {
    id: 'pop-arn',
    code: 'ARN',
    region: 'EU-North (Stockholm)',
    location: 'Stockholm',
    country: 'Sweden',
    coordinates: [59.3293, 18.0686],
    tier: 2,
    status: 'optimal',
    ttfbMs: 14.8,
    tlsRtt: '1.4ms (0-RTT)',
    http3: true,
    activeProbes: 180,
    requestsPerSec: 6200,
    carbonIntensity: 0.04,
    ipPrefix: '198.51.118.0/24',
  },
  {
    id: 'pop-hel',
    code: 'HEL',
    region: 'EU-North (Helsinki)',
    location: 'Helsinki',
    country: 'Finland',
    coordinates: [60.1699, 24.9384],
    tier: 2,
    status: 'optimal',
    ttfbMs: 17.5,
    tlsRtt: '1.7ms (0-RTT)',
    http3: true,
    activeProbes: 150,
    requestsPerSec: 5100,
    carbonIntensity: 0.05,
    ipPrefix: '198.51.119.0/24',
  },
  {
    id: 'pop-waw',
    code: 'WAW',
    region: 'EU-East (Warsaw)',
    location: 'Warsaw',
    country: 'Poland',
    coordinates: [52.2297, 21.0122],
    tier: 2,
    status: 'optimal',
    ttfbMs: 18.9,
    tlsRtt: '1.8ms (0-RTT)',
    http3: true,
    activeProbes: 160,
    requestsPerSec: 5400,
    carbonIntensity: 0.42,
    ipPrefix: '198.51.120.0/24',
  },
  {
    id: 'pop-ist',
    code: 'IST',
    region: 'EU-Southeast (Istanbul)',
    location: 'Istanbul',
    country: 'Turkey',
    coordinates: [41.0082, 28.9784],
    tier: 2,
    status: 'degraded',
    ttfbMs: 29.8,
    tlsRtt: '3.4ms (0-RTT)',
    http3: true,
    activeProbes: 130,
    requestsPerSec: 4200,
    carbonIntensity: 0.33,
    ipPrefix: '198.51.121.0/24',
  },
  {
    id: 'pop-dxb',
    code: 'DXB',
    region: 'ME-Central (Dubai)',
    location: 'Dubai',
    country: 'United Arab Emirates',
    coordinates: [25.2048, 55.2708],
    tier: 1,
    status: 'optimal',
    ttfbMs: 16.4,
    tlsRtt: '1.6ms (0-RTT)',
    http3: true,
    activeProbes: 280,
    requestsPerSec: 10400,
    carbonIntensity: 0.38,
    ipPrefix: '198.51.122.0/24',
  },

  // Africa
  {
    id: 'pop-jnb',
    code: 'JNB',
    region: 'AF-South (Johannesburg)',
    location: 'Johannesburg',
    country: 'South Africa',
    coordinates: [-26.2041, 28.0473],
    tier: 2,
    status: 'optimal',
    ttfbMs: 31.5,
    tlsRtt: '3.0ms (0-RTT)',
    http3: true,
    activeProbes: 140,
    requestsPerSec: 4600,
    carbonIntensity: 0.58,
    ipPrefix: '198.51.123.0/24',
  },
  {
    id: 'pop-cpt',
    code: 'CPT',
    region: 'AF-South (Cape Town)',
    location: 'Cape Town',
    country: 'South Africa',
    coordinates: [-33.9249, 18.4241],
    tier: 3,
    status: 'optimal',
    ttfbMs: 35.8,
    tlsRtt: '3.6ms (0-RTT)',
    http3: true,
    activeProbes: 90,
    requestsPerSec: 2700,
    carbonIntensity: 0.52,
    ipPrefix: '198.51.124.0/24',
  },
  {
    id: 'pop-nbo',
    code: 'NBO',
    region: 'AF-East (Nairobi)',
    location: 'Nairobi',
    country: 'Kenya',
    coordinates: [-1.2921, 36.8219],
    tier: 3,
    status: 'degraded',
    ttfbMs: 44.2,
    tlsRtt: '4.8ms (1-RTT fallback)',
    http3: false,
    activeProbes: 75,
    requestsPerSec: 1900,
    carbonIntensity: 0.12,
    ipPrefix: '198.51.125.0/24',
  },

  // Asia-Pacific
  {
    id: 'pop-bom',
    code: 'BOM',
    region: 'AP-South (Mumbai)',
    location: 'Mumbai',
    country: 'India',
    coordinates: [19.0760, 72.8777],
    tier: 1,
    status: 'optimal',
    ttfbMs: 17.6,
    tlsRtt: '1.7ms (0-RTT)',
    http3: true,
    activeProbes: 310,
    requestsPerSec: 11500,
    carbonIntensity: 0.49,
    ipPrefix: '198.51.126.0/24',
  },
  {
    id: 'pop-del',
    code: 'DEL',
    region: 'AP-North (New Delhi)',
    location: 'New Delhi',
    country: 'India',
    coordinates: [28.6139, 77.2090],
    tier: 2,
    status: 'optimal',
    ttfbMs: 20.3,
    tlsRtt: '2.0ms (0-RTT)',
    http3: true,
    activeProbes: 190,
    requestsPerSec: 6700,
    carbonIntensity: 0.56,
    ipPrefix: '198.51.127.0/24',
  },
  {
    id: 'pop-sin',
    code: 'SIN',
    region: 'AP-Southeast (Singapore)',
    location: 'Singapore',
    country: 'Singapore',
    coordinates: [1.3521, 103.8198],
    tier: 1,
    status: 'optimal',
    ttfbMs: 11.2,
    tlsRtt: '1.1ms (0-RTT)',
    http3: true,
    activeProbes: 390,
    requestsPerSec: 14800,
    carbonIntensity: 0.29,
    ipPrefix: '198.51.128.0/24',
  },
  {
    id: 'pop-kul',
    code: 'KUL',
    region: 'AP-Southeast (Kuala Lumpur)',
    location: 'Kuala Lumpur',
    country: 'Malaysia',
    coordinates: [3.1390, 101.6869],
    tier: 2,
    status: 'optimal',
    ttfbMs: 16.7,
    tlsRtt: '1.7ms (0-RTT)',
    http3: true,
    activeProbes: 160,
    requestsPerSec: 5200,
    carbonIntensity: 0.35,
    ipPrefix: '198.51.129.0/24',
  },
  {
    id: 'pop-bkk',
    code: 'BKK',
    region: 'AP-Southeast (Bangkok)',
    location: 'Bangkok',
    country: 'Thailand',
    coordinates: [13.7563, 100.5018],
    tier: 2,
    status: 'optimal',
    ttfbMs: 19.4,
    tlsRtt: '1.9ms (0-RTT)',
    http3: true,
    activeProbes: 150,
    requestsPerSec: 4900,
    carbonIntensity: 0.34,
    ipPrefix: '198.51.130.0/24',
  },
  {
    id: 'pop-jkt',
    code: 'JKT',
    region: 'AP-Southeast (Jakarta)',
    location: 'Jakarta',
    country: 'Indonesia',
    coordinates: [-6.2088, 106.8456],
    tier: 2,
    status: 'degraded',
    ttfbMs: 27.9,
    tlsRtt: '2.9ms (0-RTT)',
    http3: true,
    activeProbes: 140,
    requestsPerSec: 4500,
    carbonIntensity: 0.46,
    ipPrefix: '198.51.131.0/24',
  },
  {
    id: 'pop-mnl',
    code: 'MNL',
    region: 'AP-Southeast (Manila)',
    location: 'Manila',
    country: 'Philippines',
    coordinates: [14.5995, 120.9842],
    tier: 3,
    status: 'optimal',
    ttfbMs: 25.1,
    tlsRtt: '2.5ms (0-RTT)',
    http3: true,
    activeProbes: 110,
    requestsPerSec: 3300,
    carbonIntensity: 0.41,
    ipPrefix: '198.51.132.0/24',
  },
  {
    id: 'pop-hkg',
    code: 'HKG',
    region: 'AP-East (Hong Kong)',
    location: 'Hong Kong',
    country: 'Hong Kong SAR',
    coordinates: [22.3193, 114.1694],
    tier: 1,
    status: 'optimal',
    ttfbMs: 12.1,
    tlsRtt: '1.2ms (0-RTT)',
    http3: true,
    activeProbes: 360,
    requestsPerSec: 13400,
    carbonIntensity: 0.37,
    ipPrefix: '198.51.133.0/24',
  },
  {
    id: 'pop-tpe',
    code: 'TPE',
    region: 'AP-East (Taipei)',
    location: 'Taipei',
    country: 'Taiwan',
    coordinates: [25.0330, 121.5654],
    tier: 1,
    status: 'optimal',
    ttfbMs: 13.5,
    tlsRtt: '1.3ms (0-RTT)',
    http3: true,
    activeProbes: 310,
    requestsPerSec: 11100,
    carbonIntensity: 0.36,
    ipPrefix: '198.51.134.0/24',
  },
  {
    id: 'pop-icn',
    code: 'ICN',
    region: 'AP-Northeast (Seoul)',
    location: 'Seoul / Incheon',
    country: 'South Korea',
    coordinates: [37.5665, 126.9780],
    tier: 1,
    status: 'optimal',
    ttfbMs: 10.9,
    tlsRtt: '1.1ms (0-RTT)',
    http3: true,
    activeProbes: 370,
    requestsPerSec: 13900,
    carbonIntensity: 0.32,
    ipPrefix: '198.51.135.0/24',
  },
  {
    id: 'pop-nrt',
    code: 'NRT',
    region: 'AP-Northeast (Tokyo)',
    location: 'Tokyo / Narita',
    country: 'Japan',
    coordinates: [35.6762, 139.6503],
    tier: 1,
    status: 'optimal',
    ttfbMs: 9.5,
    tlsRtt: '0.95ms (0-RTT)',
    http3: true,
    activeProbes: 440,
    requestsPerSec: 16800,
    carbonIntensity: 0.26,
    ipPrefix: '198.51.136.0/24',
  },
  {
    id: 'pop-kix',
    code: 'KIX',
    region: 'AP-Northeast (Osaka)',
    location: 'Osaka / Kansai',
    country: 'Japan',
    coordinates: [34.6937, 135.5023],
    tier: 2,
    status: 'optimal',
    ttfbMs: 12.3,
    tlsRtt: '1.2ms (0-RTT)',
    http3: true,
    activeProbes: 210,
    requestsPerSec: 7300,
    carbonIntensity: 0.24,
    ipPrefix: '198.51.137.0/24',
  },
  {
    id: 'pop-syd',
    code: 'SYD',
    region: 'OC-East (Sydney)',
    location: 'Sydney',
    country: 'Australia',
    coordinates: [-33.8688, 151.2093],
    tier: 1,
    status: 'optimal',
    ttfbMs: 15.2,
    tlsRtt: '1.5ms (0-RTT)',
    http3: true,
    activeProbes: 330,
    requestsPerSec: 11900,
    carbonIntensity: 0.44,
    ipPrefix: '198.51.138.0/24',
  },
  {
    id: 'pop-mel',
    code: 'MEL',
    region: 'OC-South (Melbourne)',
    location: 'Melbourne',
    country: 'Australia',
    coordinates: [-37.8136, 144.9631],
    tier: 2,
    status: 'optimal',
    ttfbMs: 18.0,
    tlsRtt: '1.8ms (0-RTT)',
    http3: true,
    activeProbes: 180,
    requestsPerSec: 6100,
    carbonIntensity: 0.51,
    ipPrefix: '198.51.139.0/24',
  },
  {
    id: 'pop-per',
    code: 'PER',
    region: 'OC-West (Perth)',
    location: 'Perth',
    country: 'Australia',
    coordinates: [-31.9505, 115.8605],
    tier: 2,
    status: 'optimal',
    ttfbMs: 26.4,
    tlsRtt: '2.6ms (0-RTT)',
    http3: true,
    activeProbes: 130,
    requestsPerSec: 4100,
    carbonIntensity: 0.43,
    ipPrefix: '198.51.140.0/24',
  },
  {
    id: 'pop-akl',
    code: 'AKL',
    region: 'OC-Pacific (Auckland)',
    location: 'Auckland',
    country: 'New Zealand',
    coordinates: [-36.8485, 174.7633],
    tier: 3,
    status: 'optimal',
    ttfbMs: 29.1,
    tlsRtt: '2.9ms (0-RTT)',
    http3: true,
    activeProbes: 95,
    requestsPerSec: 2900,
    carbonIntensity: 0.08,
    ipPrefix: '198.51.141.0/24',
  },
];

export const TOTAL_POPS_COUNT = EDGE_POPS.length; // 42

export const TIER_1_POPS = EDGE_POPS.filter((pop) => pop.tier === 1);
export const TIER_2_POPS = EDGE_POPS.filter((pop) => pop.tier <= 2);
export const TIER_3_POPS = EDGE_POPS;

export function getPoPsByPlan(planTier: 'free' | 'pro' | 'team' | 'enterprise'): EdgePoP[] {
  switch (planTier) {
    case 'free':
      return EDGE_POPS.slice(0, 6);
    case 'pro':
      return EDGE_POPS.slice(0, 14);
    case 'team':
      return EDGE_POPS.slice(0, 26);
    case 'enterprise':
    default:
      return EDGE_POPS;
  }
}

export function findPoPById(id: string): EdgePoP | undefined {
  return EDGE_POPS.find((pop) => pop.id === id || pop.code.toLowerCase() === id.toLowerCase());
}

export function getPoPStats() {
  const optimalCount = EDGE_POPS.filter((p) => p.status === 'optimal').length;
  const degradedCount = EDGE_POPS.filter((p) => p.status === 'degraded').length;
  const criticalCount = EDGE_POPS.filter((p) => p.status === 'critical').length;
  const latencies = EDGE_POPS.map((p) => p.ttfbMs).sort((a, b) => a - b);
  const avgLatency = Number((latencies.reduce((a, b) => a + b, 0) / latencies.length).toFixed(1));
  const p95Latency = Number(latencies[Math.floor(latencies.length * 0.95)].toFixed(1));
  const totalReqSec = EDGE_POPS.reduce((sum, p) => sum + p.requestsPerSec, 0);

  return {
    totalPoPs: EDGE_POPS.length,
    optimalCount,
    degradedCount,
    criticalCount,
    avgLatency,
    p95Latency,
    totalReqSec,
  };
}
