import type { Metadata } from 'next';
import { Inter, JetBrains_Mono } from 'next/font/google';
import './globals.css';
import { Providers } from '@/components/Providers';
import { AppProvider } from '@/lib/context';
import { CommandPalette } from '@/components/CommandPalette';
import { SetupScreen } from '@/components/SetupScreen';
import { AuthProvider } from '@/components/AuthProvider';
import { MobileNavWrapper } from '@/components/MobileNavWrapper';
import ErrorBoundary from '@/components/ErrorBoundary';
import { Suspense } from 'react';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
  display: 'swap',
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ['latin'],
  variable: '--font-mono',
  display: 'swap',
});

export const metadata: Metadata = {
  // ── Core ──────────────────────────────────────────────
  metadataBase: new URL('https://catalystlab.tech'),
  title: {
    default: 'CatalystLab — Think at the edge of knowledge',
    template: '%s · CatalystLab',
  },
  description:
    'AI-powered research brainstorming and literature discovery. ' +
    '20 instruments · 9 academic sources · Free forever plan.',
  keywords: [
    'research tool',
    'AI brainstorming',
    'literature discovery',
    'academic research',
    'research instruments',
    'Gemini AI',
    'Semantic Scholar',
    'arXiv',
    'PhD tools',
    'graduate research',
    'thought collider',
    'pressure chamber',
    'research gap finder',
    'CatalystLab',
  ],
  authors: [{ name: 'CatalystLab', url: 'https://catalystlab.tech' }],
  creator: 'CatalystLab',
  publisher: 'CatalystLab',

  // ── Robots ────────────────────────────────────────────
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },

  // ── Canonical ─────────────────────────────────────────
  alternates: {
    canonical: 'https://catalystlab.tech',
  },

  // ── Open Graph (WhatsApp, LinkedIn, Facebook, Slack) ──
  openGraph: {
    type: 'website',
    url: 'https://catalystlab.tech',
    siteName: 'CatalystLab',
    title: 'CatalystLab — Think at the edge of knowledge',
    description:
      'AI-powered research brainstorming + automatic literature discovery. ' +
      '20 instruments · 9 academic sources · Free forever plan.',
    locale: 'en_US',
    images: [
      {
        url: '/og-image.png',       // generated by app/og-image.png/route.tsx below
        width: 1200,
        height: 630,
        alt: 'CatalystLab — Think at the edge of knowledge',
        type: 'image/png',
      },
    ],
  },

  // ── Twitter / X ───────────────────────────────────────
  twitter: {
    card: 'summary_large_image',
    site: '@catalystlab',          // update if you create a Twitter account
    creator: '@catalystlab',
    title: 'CatalystLab — Think at the edge of knowledge',
    description:
      'AI brainstorming + live literature discovery for researchers. ' +
      '20 instruments · 9 sources · Free.',
    images: ['/og-image.png'],
  },

  // ── Icons (all sizes, no separate files needed) ───────
  icons: {
    icon: [
      { url: '/favicon.svg', type: 'image/svg+xml' },
      { url: '/favicon-32.png', sizes: '32x32', type: 'image/png' },
      { url: '/favicon-16.png', sizes: '16x16', type: 'image/png' },
    ],
    apple: [
      { url: '/apple-icon.png', sizes: '180x180', type: 'image/png' },
    ],
    shortcut: '/favicon.svg',
  },

  // ── PWA / theme ───────────────────────────────────────
  manifest: '/manifest.json',
  themeColor: [
    { media: '(prefers-color-scheme: dark)', color: '#0c0c0f' },
    { media: '(prefers-color-scheme: light)', color: '#0c0c0f' },
  ],
  colorScheme: 'dark',
  viewport: {
    width: 'device-width',
    initialScale: 1,
    maximumScale: 1,
  },

  // ── Verification (add later when you verify site) ─────
  // verification: {
  //   google: 'your-google-site-verification-token',
  // },

  // ── App info ──────────────────────────────────────────
  applicationName: 'CatalystLab',
  category: 'Education',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning className={`${inter.variable} ${jetbrainsMono.variable}`}>
      <body suppressHydrationWarning className="bg-[#0c0c0f] text-[#eeeef2] selection:bg-[var(--bg-selection)] overflow-x-hidden max-w-full">
        <a href="#main-content" className="sr-only focus:not-sr-only focus:absolute focus:top-4 focus:left-4 focus:z-50 focus:bg-[#5b5bf6] focus:text-white focus:px-4 focus:py-2 focus:rounded-lg">
          Skip to content
        </a>
        <Providers>
          <ErrorBoundary>
            <AuthProvider>
              <AppProvider>
                <SetupScreen>
                  <CommandPalette />
                  <Suspense fallback={
                    <div className="min-h-screen bg-[#0c0c0f] flex items-center justify-center">
                      <div className="flex gap-1.5">
                        {[0, 1, 2].map(i => (
                          <div key={i} className="w-1.5 h-1.5 rounded-full bg-[#5b5bf6] animate-bounce" style={{ animationDelay: `${i * 0.15}s` }} />
                        ))}
                      </div>
                    </div>
                  }>
                    {children}
                  </Suspense>
                  <MobileNavWrapper />
                </SetupScreen>
              </AppProvider>
            </AuthProvider>
          </ErrorBoundary>
        </Providers>
      </body>
    </html>
  );
}
