query ListAllProjects @auth(level: USER, insecureReason: "This operation is safe to expose to all logged in users.") {
  projects {
    id
    name
    status
    startDate
    endDate
    description
    principalInvestigator {
      id
      displayName
      email
    }
  }
}

mutation CreateNewExperiment($name: String!, $experimentDate: Date!, $status: String!, $projectId: UUID!, $experimentLeadId: UUID) @auth(level: USER) {
  experiment_insert(data: {
    name: $name,
    experimentDate: $experimentDate,
    status: $status,
    projectId: $projectId,
    experimentLeadId: $experimentLeadId
  })
}

query GetMyExperiments @auth(level: USER) {
  experiments(where: {experimentLead: {id_expr: "auth.uid"}}) {
    id
    name
    experimentDate
    status
    project {
      name
    }
    observations_on_experiment {
      id
      observationDate
      value
      unit
    }
  }
}

mutation RecordObservation($experimentId: UUID!, $observationDate: Date!, $value: String!, $unit: String!, $notes: String, $attachmentUrl: String) @auth(level: USER) {
  observation_insert(data: {
    experimentId: $experimentId,
    observationDate: $observationDate,
    value: $value,
    unit: $unit,
    notes: $notes,
    attachmentUrl: $attachmentUrl
  })
}