import { GoogleAuthProvider, signInWithPopup, onAuthStateChanged } from 'firebase/auth';
import { auth } from './firebase';

let cachedFormsToken: string | null = null;

// Track if current user logs out or changes to safely clear the cached Google Forms token
onAuthStateChanged(auth, (user) => {
  if (!user) {
    cachedFormsToken = null;
  }
});

/**
 * Ensures we have a valid Google access token with the Forms scope.
 * Uses incremental consent via Firebase Auth popup if the token is not cached.
 */
export async function getGoogleFormsToken(): Promise<string> {
  if (cachedFormsToken) {
    return cachedFormsToken;
  }

  const provider = new GoogleAuthProvider();
  // Request read/write access to Google Forms
  provider.addScope('https://www.googleapis.com/auth/forms');

  const result = await signInWithPopup(auth, provider);
  const credential = GoogleAuthProvider.credentialFromResult(result);

  if (!credential?.accessToken) {
    throw new Error('Google Forms authorization was successful, but no access token was returned.');
  }

  cachedFormsToken = credential.accessToken;
  return cachedFormsToken;
}

/**
 * Creates a fully customized, professional academic evaluation and feedback form in Google Forms.
 * Returns the responder URI (link to fill out the form).
 */
export async function createAcademicQuizForm(
  synthesisText: string,
  instrumentName: string,
  onProgress?: (msg: string) => void
): Promise<string> {
  if (!synthesisText) {
    throw new Error('Cannot generate an assessment with empty synthesis report contents.');
  }

  // 1. Authenticate with Google Forms scope
  onProgress?.('Authorizing with Google account...');
  const accessToken = await getGoogleFormsToken();

  // 2. Fetch questions from Gemini server-side helper API
  onProgress?.('Generating assessment questions using Gemini AI...');
  const quizRes = await fetch('/api/generate-quiz', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      synthesis: synthesisText.substring(0, 15000), // safe truncation for prompt limits
      instrumentName,
    }),
  });

  if (!quizRes.ok) {
    const errorText = await quizRes.text();
    throw new Error(`Failed to generate questionnaire content: ${errorText}`);
  }

  const { questions } = await quizRes.json();

  if (!questions || !Array.isArray(questions) || questions.length === 0) {
    throw new Error('No valid assessment questions could be generated by Gemini.');
  }

  // 3. Create the empty Google Form
  onProgress?.('Creating empty Google Form...');
  const formTitle = `Peer Evaluation & Review: ${instrumentName}`;
  const createFormRes = await fetch('https://forms.googleapis.com/v1/forms', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${accessToken}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      info: {
        title: formTitle,
        documentTitle: `CatalystLab Academic Assessment - ${instrumentName}`,
        description: `This automated assessment gathers feedback and review parameters regarding the AI-synthesized research report conducted under ${instrumentName}.`
      },
    }),
  });

  if (!createFormRes.ok) {
    const errText = await createFormRes.text();
    throw new Error(`Google Forms API failed to create document: ${errText}`);
  }

  const formData = await createFormRes.json();
  const formId = formData.formId;
  const responderUri = formData.responderUri;

  if (!formId || !responderUri) {
    throw new Error('Successfully created Form, but Google did not return a valid identifier or direct link.');
  }

  // 4. Transform generated questions into Google Forms createItem requests
  onProgress?.('Populating questions and formatting peer review fields...');
  const batchRequests: any[] = [];

  // Add field 0: Academic identity / Name
  batchRequests.push({
    createItem: {
      item: {
        title: 'Reviewer Full Name & Scientific Affiliation',
        description: 'Provide your name and academic credentials to log peer evaluation metadata.',
        questionItem: {
          question: {
            required: true,
            textQuestion: {
              paragraph: false
            }
          }
        }
      },
      location: {
        index: 0
      }
    }
  });

  // Add the dynamic AI questions
  questions.forEach((q: any, idx: number) => {
    batchRequests.push({
      createItem: {
        item: {
          title: q.title || `Research Evaluation Parameter ${idx + 1}`,
          questionItem: {
            question: {
              required: true,
              choiceQuestion: {
                type: 'RADIO',
                options: (q.options || ['Strongly Agree', 'Neutral', 'Strongly Disagree']).map((opt: string) => ({
                  value: opt
                }))
              }
            }
          }
        },
        location: {
          index: idx + 1
        }
      }
    });
  });

  // Add dynamic feedback text field at the end
  batchRequests.push({
    createItem: {
      item: {
        title: 'Deep Peer Comments / Theoretical Criticisms',
        description: 'Detail any challenges, potential flaws, or future extension suggestions for this literature review.',
        questionItem: {
          question: {
            required: false,
            textQuestion: {
              paragraph: true
            }
          }
        }
      },
      location: {
        index: questions.length + 1
      }
    }
  });

  // 5. Run batchUpdate inside the Form
  const batchRes = await fetch(`https://forms.googleapis.com/v1/forms/${formId}:batchUpdate`, {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${accessToken}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      requests: batchRequests
    }),
  });

  if (!batchRes.ok) {
    const errText = await batchRes.text();
    throw new Error(`Failed to configure google Form fields in batch update: ${errText}`);
  }

  return responderUri;
}
