import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';
import type { AuditReport } from '../types';
import { ENGINES_MAP } from '../data/engines';

export async function exportReportToPdf(elementId: string, filename: string = 'CatalystLab-Audit-Report.pdf'): Promise<void> {
  const element = document.getElementById(elementId);
  if (!element) {
    throw new Error(`Element with id '${elementId}' not found.`);
  }

  try {
    const canvas = await html2canvas(element, {
      scale: 2,
      backgroundColor: '#020617',
      useCORS: true,
      logging: false,
      windowWidth: element.scrollWidth,
      windowHeight: element.scrollHeight
    });

    const imgData = canvas.toDataURL('image/jpeg', 0.95);
    const pdf = new jsPDF('p', 'mm', 'a4');
    const pageWidth = 210;
    const pageHeight = 297;
    const imgWidth = pageWidth;
    const imgHeight = (canvas.height * imgWidth) / canvas.width;
    
    let heightLeft = imgHeight;
    let position = 0;

    pdf.addImage(imgData, 'JPEG', 0, position, imgWidth, imgHeight);
    heightLeft -= pageHeight;

    while (heightLeft > 0) {
      position = heightLeft - imgHeight;
      pdf.addPage();
      pdf.addImage(imgData, 'JPEG', 0, position, imgWidth, imgHeight);
      heightLeft -= pageHeight;
    }

    pdf.save(filename);
  } catch (error) {
    console.error('PDF export failed, falling back to browser print:', error);
    window.print();
  }
}

/**
 * Generate standalone PDF directly from AuditReport data structure using browser canvas
 */
export async function exportAuditReportDataToPdf(report: AuditReport): Promise<void> {
  const meta = ENGINES_MAP[report.engine] || { name: report.engine, icon: 'bolt' };
  const dateStr = report.createdAt ? new Date(report.createdAt).toLocaleString() : new Date().toLocaleString();
  
  // Create an off-screen container styled for high-resolution PDF rendering
  const container = document.createElement('div');
  container.style.position = 'fixed';
  container.style.left = '-9999px';
  container.style.top = '0';
  container.style.width = '800px';
  container.style.backgroundColor = '#020617';
  container.style.color = '#f8fafc';
  container.style.fontFamily = "'JetBrains Mono', monospace";
  container.style.padding = '32px';
  container.style.boxSizing = 'border-box';
  container.style.zIndex = '-9999';

  let domain = report.url;
  try {
    domain = new URL(report.url.startsWith('http') ? report.url : `https://${report.url}`).hostname;
  } catch {}

  container.innerHTML = `
    <div style="border-bottom: 2px solid #38bdf8; padding-bottom: 16px; margin-bottom: 24px;">
      <div style="display: flex; justify-content: space-between; align-items: center;">
        <div style="font-size: 20px; font-weight: bold; color: #f97316;">
          &gt;_ CatalystLab Telemetry Dossier
        </div>
        <div style="font-size: 12px; color: #94a3b8;">
          ID: ${report.id || 'N/A'}
        </div>
      </div>
      <div style="font-size: 16px; font-weight: bold; color: #ffffff; margin-top: 8px;">
        [${meta.name}] — ${domain}
      </div>
      <div style="font-size: 12px; color: #64748b; margin-top: 4px;">
        Target: ${report.url} | Timestamp: ${dateStr}
      </div>
    </div>
    <div style="background-color: #0b0f19; border: 1px solid #1e293b; border-radius: 8px; padding: 20px; font-size: 11px; line-height: 1.5; white-space: pre-wrap; color: #cbd5e1;">
      ${report.output || 'No output recorded.'}
    </div>
    <div style="margin-top: 24px; padding-top: 12px; border-top: 1px solid #1e293b; font-size: 10px; color: #64748b; text-align: center;">
      Verified Telemetry Dossier • Generated by CatalystLab Enterprise Health Engine • https://www.catalystlab.tech
    </div>
  `;

  document.body.appendChild(container);

  try {
    const canvas = await html2canvas(container, {
      scale: 2,
      backgroundColor: '#020617',
      useCORS: true
    });

    const imgData = canvas.toDataURL('image/jpeg', 0.95);
    const pdf = new jsPDF('p', 'mm', 'a4');
    const pageWidth = 210;
    const pageHeight = 297;
    const imgWidth = pageWidth;
    const imgHeight = (canvas.height * imgWidth) / canvas.width;
    
    let heightLeft = imgHeight;
    let position = 0;

    pdf.addImage(imgData, 'JPEG', 0, position, imgWidth, imgHeight);
    heightLeft -= pageHeight;

    while (heightLeft > 0) {
      position = heightLeft - imgHeight;
      pdf.addPage();
      pdf.addImage(imgData, 'JPEG', 0, position, imgWidth, imgHeight);
      heightLeft -= pageHeight;
    }

    const safeDomain = domain.replace(/[^a-zA-Z0-9]/g, '_');
    pdf.save(`CatalystLab-${safeDomain}-${report.engine}.pdf`);
  } catch (err) {
    console.error("Direct PDF export error:", err);
    window.print();
  } finally {
    document.body.removeChild(container);
  }
}
